# frozen_string_literal: true

require 'bundler/gem_tasks'
require 'rake/testtask'

Rake::TestTask.new(:test) do |t|
  t.libs << 'test'
  t.libs << 'lib'
  t.test_files = FileList['test/**/*_test.rb']
end

file 'lib/ecoji/emojis.rb' => %w[dep/ecoji/emojisV1.txt dep/ecoji/emojisV2.txt] do
  v1 = File.read('dep/ecoji/emojisV1.txt').lines(chomp: true)
  v2 = File.read('dep/ecoji/emojisV2.txt').lines(chomp: true)

  source = []
  source << '# This file is generated by `rake generate`.'
  source << ''
  source << 'module Ecoji::Emojis'
  source << '  V1 = ['
  v1.each { |hex| source << "    0x#{hex}," }
  source << '  ]'
  source << ''
  source << '  V2 = ['
  v2.each { |hex| source << "    0x#{hex}," }
  source << '  ]'
  source << 'end'

  File.write 'lib/ecoji/emojis.rb', source.join("\n")
end

task generate: %w[lib/ecoji/emojis.rb]

task default: :test
