name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - name: Install Ruby dependencies
        run: bundle install
      - name: Install Node dependencies
        run: yarn install --frozen-lockfile
      - name: Run tests
        run: bundle exec rake test
      - name: Check generated code
        run: |
          bundle exec rake generate
          git diff --exit-code
      - name: Check web app code format
        run: yarn check-format
